[package]
name = "balance-api"
version = "0.1.0"
edition = "2024"

[dependencies]

# Async runtime
tokio = { version = "1.44.1", features = ["full"] }
tokio-util = "0.7.14"

# Serialization
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.105"
protobuf = "3.7.2"


# HTTP and API Clients
reqwest = "0.12.15"
hyper = "1.6.0"

# Error Handling
anyhow = "1.0.97"
thiserror = "2.0.12"

# Database
clickhouse = "0.13.2"
redis = { version = "0.29.2", features = ["tokio-comp"] }

# Messaging
rdkafka = { version = "0.37.0", features = ["cmake-build"] }

# Configuration
dotenv = "0.15.0"
config = "0.15.11"

# API Frameworks
async-graphql = { version = "7.0", features = ["chrono", "decimal"] }
tonic = "0.13.0"
tower = "0.5.2"
axum = "0.7"


# Decimal Handling
rust_decimal = "1.37.1"
rust_decimal_macros = "1.37.1"

# Utilities
chrono = "0.4.40"
uuid = { version = "1.6", features = ["v4", "serde"] }
futures = "0.3.31"
hex = "0.4.3"
polars-arrow = "0.46.0"
hypersync-client = { path = "../hypersync-client-rust/hypersync-client" }
url = "2.5.4"

# Logging
log = "0.4.27"
env_logger = "0.11.8"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tokio-macros = "2.1.0"
clickhouse = { version = "0.13.2", features = ["test-util"] }
mockall = "0.12.1"

[profile.release]
lto = true
